# Stage 1: Build
FROM node:22-alpine AS build

WORKDIR /app

COPY package.json ./

RUN npm install

ARG VITE_AZURE_CLIENT_ID
ARG VITE_AZURE_AUTHORITY
ARG VITE_AZURE_REDIRECT_URI
ARG VITE_AZURE_SCOPE
ARG VITE_AUTH_SERVICE_URL
ARG VITE_CHAT_SERVICE_URL
ARG VITE_DOCUMENT_SERVICE_URL
ENV VITE_AZURE_CLIENT_ID=$VITE_AZURE_CLIENT_ID
ENV VITE_AZURE_AUTHORITY=$VITE_AZURE_AUTHORITY
ENV VITE_AZURE_REDIRECT_URI=$VITE_AZURE_REDIRECT_URI
ENV VITE_AZURE_SCOPE=$VITE_AZURE_SCOPE
ENV VITE_AUTH_SERVICE_URL=$VITE_AUTH_SERVICE_URL
ENV VITE_CHAT_SERVICE_URL=$VITE_CHAT_SERVICE_URL
ENV VITE_DOCUMENT_SERVICE_URL=$VITE_DOCUMENT_SERVICE_URL

COPY . .

RUN npm run build-only

# Stage 2: Serve with nginx
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
